Repository BrainPix/BrainPix-Back, pull requests merged in 2025-02, with the labels that each got.

#86 [CICD] 몽고디비 관련 yml 파일 추가 (#85)
  src/main/resources/application-dev.yml
Labels: 🖧 cicd

#88 [REFACT] 아이디어 마켓 API URI 수정 (#87)
  src/main/java/com/brainpix/post/controller/IdeaMarketController.java
Labels: ♻️ refactoring

#90 [FEAT] 로그인 처리를 위한 메일 전송 구현 ($76)
  build.gradle
  src/main/java/com/brainpix/api/code/error/MailErrorCode.java
  src/main/java/com/brainpix/config/KafkaConsumerConfig.java
  src/main/java/com/brainpix/config/MailConfig.java
  src/main/java/com/brainpix/kafka/service/MailEventListener.java
  src/main/java/com/brainpix/kafka/service/MailEventService.java
  src/main/java/com/brainpix/mail/controller/MailController.java
  src/main/java/com/brainpix/mail/dto/SendMailDto.java
  src/main/java/com/brainpix/mail/service/MailService.java
Labels: ✨ feature

#64 [FEAT] 요청 과제 지원 api 구현
  src/main/java/com/brainpix/api/code/error/RequestTaskErrorCode.java
  src/main/java/com/brainpix/joining/entity/purchasing/RequestTaskPurchasing.java
  src/main/java/com/brainpix/joining/repository/RequestTaskPurchasingRepository.java
  src/main/java/com/brainpix/post/controller/RequestTaskCommandController.java
  src/main/java/com/brainpix/post/converter/ApplyRequestTaskDtoConverter.java
  src/main/java/com/brainpix/post/dto/ApplyRequestTaskDto.java
  src/main/java/com/brainpix/post/service/RequestTaskCommandService.java
Labels: ✨ feature

#94 [FEAT] 로그인 및 인증 인가 처리
  build.gradle
  src/main/java/com/brainpix/api/code/error/AuthorityErrorCode.java
  src/main/java/com/brainpix/config/WebMvcConfig.java
  src/main/java/com/brainpix/security/AuthenticationManagerConfig.java
  src/main/java/com/brainpix/security/SecurityConfig.java
  src/main/java/com/brainpix/security/authenticationToken/BrainpixAuthenticationToken.java
  src/main/java/com/brainpix/security/authenticationToken/CompanyAuthenticationToken.java
  src/main/java/com/brainpix/security/authenticationToken/IndividualAuthenticationToken.java
  src/main/java/com/brainpix/security/authority/BrainpixAuthority.java
  src/main/java/com/brainpix/security/authorization/AbstractAuthInterceptor.java
  src/main/java/com/brainpix/security/authorization/AllUser.java
  src/main/java/com/brainpix/security/authorization/AllUserInterceptor.java
  src/main/java/com/brainpix/security/authorization/Company.java
  src/main/java/com/brainpix/security/authorization/CompanyInterceptor.java
  src/main/java/com/brainpix/security/authorization/Individual.java
  src/main/java/com/brainpix/security/authorization/IndividualInterceptor.java
  src/main/java/com/brainpix/security/authorization/UserId.java
  src/main/java/com/brainpix/security/authorization/UserIdArgumentResolver.java
  src/main/java/com/brainpix/security/contextholder/GetAuthenticationInfo.java
  src/main/java/com/brainpix/security/controller/SignInController.java
  src/main/java/com/brainpix/security/converter/SignInConverter.java
  src/main/java/com/brainpix/security/dto/request/SignInRequest.java
  src/main/java/com/brainpix/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/brainpix/security/provider/BrainpixUserAuthenticationProvider.java
  src/main/java/com/brainpix/security/service/BrainpixUserDetailService.java
  src/main/java/com/brainpix/security/tokenManger/JwtTokenManager.java
  src/main/java/com/brainpix/security/tokenManger/TokenManager.java
  src/main/java/com/brainpix/security/userdetail/BrainpixUserDetails.java
  src/main/java/com/brainpix/user/entity/Company.java
  src/main/java/com/brainpix/user/entity/Individual.java
  src/main/java/com/brainpix/user/entity/User.java
  src/main/resources/application-dev.yml
Labels: ✨ feature

#105 [BUG] 머지 충돌 해결 (#104)
  src/main/java/com/brainpix/api/code/error/CollaborationHubErrorCode.java
  src/main/java/com/brainpix/post/service/CollaborationHubService.java
  src/main/resources/application-dev.yml
Labels: 🐞 bug

#101 [FIX] 스웨거 응답값 수정
  src/main/java/com/brainpix/alarm/controller/AlarmController.java
  src/main/java/com/brainpix/message/controller/MessageController.java
  src/main/resources/application-dev.yml
Labels: 🔨 fix

#107 [FIX] 인가 + 유저 아이디 userId로 변경 , 스웨거 설명 추가
  src/main/java/com/brainpix/joining/controller/SupportCollaborationController.java
  src/main/java/com/brainpix/joining/controller/SupportIdeaMarketController.java
  src/main/java/com/brainpix/joining/controller/SupportRequestTaskController.java
  src/main/java/com/brainpix/post/controller/SavedPostController.java
  src/main/java/com/brainpix/profile/controller/PortfolioController.java
  src/main/java/com/brainpix/profile/controller/ProfileController.java
  src/main/java/com/brainpix/profile/dto/request/PortfolioRequest.java
Labels: 🔨 fix

#92 [FEAT] 상대방이 보는 내 프로필 조회 API 구현
  src/main/java/com/brainpix/post/repository/PostRepository.java
  src/main/java/com/brainpix/profile/controller/ProfileController.java
  src/main/java/com/brainpix/profile/controller/PublicProfileController.java
  src/main/java/com/brainpix/profile/converter/ProfilePostConverter.java
  src/main/java/com/brainpix/profile/dto/PublicProfileResponseDto.java
  src/main/java/com/brainpix/profile/service/PublicProfileService.java
  src/main/java/com/brainpix/user/entity/User.java
Labels: ✨ feature

#93 [FEAT] 마이페이지 기본 화면 페이지 API 구현
  src/main/java/com/brainpix/joining/repository/CollectionGatheringRepository.java
  src/main/java/com/brainpix/joining/repository/RequestTaskPurchasingRepository.java
  src/main/java/com/brainpix/post/repository/IdeaMarketRepository.java
  src/main/java/com/brainpix/profile/controller/MyPageController.java
  src/main/java/com/brainpix/profile/dto/MyPageResponseDto.java
  src/main/java/com/brainpix/profile/service/MyPageService.java
  src/main/java/com/brainpix/user/entity/Company.java
  src/main/java/com/brainpix/user/entity/Individual.java
  src/main/java/com/brainpix/user/entity/User.java
Labels: ✨ feature

#110 [BUG] 아이디, 닉네임 중복 확인시 예외 던지도록 수정 (#109)
  src/main/java/com/brainpix/security/controller/SignUpController.java
  src/main/java/com/brainpix/security/dto/request/SignUpRequest.java
  src/main/java/com/brainpix/security/service/SignUpService.java
Labels: 🐞 bug

#112 [BUG] CORS 변경 (#111)
  src/main/java/com/brainpix/security/SecurityConfig.java
Labels: 🐞 bug

#114 [FEAT] 로그인하지 않은 사용자도 Authentication 가지도록 수정 (#113)
  src/main/java/com/brainpix/security/authenticationToken/AnonymousAuthenticationToken.java
  src/main/java/com/brainpix/security/authority/BrainpixAuthority.java
  src/main/java/com/brainpix/security/filter/JwtAuthenticationFilter.java
Labels: ✨ feature

#125 [FIX] CORS 설정 변경 (#124)
  src/main/java/com/brainpix/security/SecurityConfig.java
Labels: 🔨 fix

#91 [REFACT] Post 생성, 수정 코드 리팩토링 (#89)
  src/main/java/com/brainpix/api/code/error/CollaborationHubErrorCode.java
  src/main/java/com/brainpix/api/code/error/IdeaMarketErrorCode.java
  src/main/java/com/brainpix/api/code/error/PostErrorCode.java
  src/main/java/com/brainpix/api/code/error/RecruitmentErrorCode.java
  src/main/java/com/brainpix/api/code/error/RequestTaskErrorCode.java
  src/main/java/com/brainpix/joining/converter/CreateInitialCollectionGatheringConverter.java
  src/main/java/com/brainpix/joining/converter/CreatePriceConverter.java
  src/main/java/com/brainpix/joining/converter/CreateRequestTaskPriceConverter.java
  src/main/java/com/brainpix/joining/dto/GatheringDto.java
  src/main/java/com/brainpix/joining/dto/IdeaMarketPriceDto.java
  src/main/java/com/brainpix/joining/dto/RequestTaskPriceDto.java
  src/main/java/com/brainpix/joining/entity/quantity/BaseQuantity.java
  src/main/java/com/brainpix/joining/entity/quantity/Price.java
  src/main/java/com/brainpix/joining/service/InitialCollectionGatheringService.java
  src/main/java/com/brainpix/joining/service/PriceService.java
  src/main/java/com/brainpix/joining/service/SupportRequestTaskService.java
  src/main/java/com/brainpix/post/controller/CollaborationHubController.java
  src/main/java/com/brainpix/post/controller/IdeaMarketController.java
  src/main/java/com/brainpix/post/controller/RequestTaskCommandController.java
  src/main/java/com/brainpix/post/controller/RequestTaskRecruitmentController.java
  src/main/java/com/brainpix/post/dto/CollaborationHubApiResponseDto.java
  src/main/java/com/brainpix/post/dto/CollaborationHubCreateDto.java
  src/main/java/com/brainpix/post/dto/CollaborationRecruitmentDto.java
  src/main/java/com/brainpix/post/dto/IdeaMarketApiResponseDto.java
  src/main/java/com/brainpix/post/dto/IdeaMarketCreateDto.java
  src/main/java/com/brainpix/post/dto/IdeaMarketUpdateDto.java
  src/main/java/com/brainpix/post/dto/PostApiResponseDto.java
  src/main/java/com/brainpix/post/dto/PostDto.java
  src/main/java/com/brainpix/post/dto/RequestTaskCreateDto.java
  src/main/java/com/brainpix/post/dto/RequestTaskRecruitmentDto.java
  src/main/java/com/brainpix/post/dto/RequestTaskWithRecruitmentsDto.java
  src/main/java/com/brainpix/post/entity/Post.java
  src/main/java/com/brainpix/post/entity/request_task/RequestTask.java
  src/main/java/com/brainpix/post/entity/request_task/RequestTaskRecruitment.java
  src/main/java/com/brainpix/post/service/CollaborationHubInitialMemberService.java
  src/main/java/com/brainpix/post/service/CollaborationHubService.java
  src/main/java/com/brainpix/post/service/IdeaMarketService.java
  src/main/java/com/brainpix/post/service/RequestTaskCommandService.java
  src/main/java/com/brainpix/post/service/RequestTaskQueryService.java
  src/main/java/com/brainpix/post/service/RequestTaskRecruitmentService.java
  src/main/java/com/brainpix/post/service/SavedPostService.java
Labels: ♻️ refactoring

#122 [REFACT] POST 생성, 수정, 삭제 관련 유저 인가 설정 및 스웨거 설명 추가
  src/main/java/com/brainpix/post/controller/CollaborationHubController.java
  src/main/java/com/brainpix/post/controller/IdeaMarketController.java
  src/main/java/com/brainpix/post/controller/RequestTaskCommandController.java
Labels: ♻️ refactoring

#136 [CICD] pull request를 위한 github action 스크립트 작성
  .github/workflows/check_build_and_merge_simulation.yml
Labels: 🖧 cicd

#118 [REFACT] 아이디어 조회 관련 리팩토링 (#116)
  src/main/java/com/brainpix/post/controller/IdeaMarketController.java
  src/main/java/com/brainpix/post/converter/GetIdeaDetailDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetIdeaListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetPopularIdeaListDtoConverter.java
  src/main/java/com/brainpix/post/dto/GetIdeaDetailDto.java
  src/main/java/com/brainpix/post/dto/GetIdeaListDto.java
  src/main/java/com/brainpix/post/dto/GetPopularIdeaListDto.java
  src/main/java/com/brainpix/post/service/IdeaMarketService.java
Labels: ✨ feature, ♻️ refactoring

#119 [REFACT] 요청 과제 조회 관련 리팩토링 (#117)
  src/main/java/com/brainpix/post/controller/RequestTaskQueryController.java
  src/main/java/com/brainpix/post/converter/GetRequestTaskDetailDtoConverter.java
  src/main/java/com/brainpix/post/dto/GetRequestTaskDetailDto.java
  src/main/java/com/brainpix/post/dto/GetRequestTaskListDto.java
  src/main/java/com/brainpix/post/service/RequestTaskQueryService.java
Labels: ✨ feature, ♻️ refactoring

#123 [REFACT] 협업 광장 조회 관련 리팩토링 (#120)
  src/main/java/com/brainpix/post/controller/CollaborationHubController.java
  src/main/java/com/brainpix/post/converter/GetCollaborationHubDetailDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetCollaborationHubListDtoConverter.java
  src/main/java/com/brainpix/post/dto/GetCollaborationHubDetailDto.java
  src/main/java/com/brainpix/post/dto/GetCollaborationHubListDto.java
  src/main/java/com/brainpix/post/service/CollaborationHubService.java
Labels: ✨ feature, ♻️ refactoring

#126 [DOCS] 알림 관련 api 명세 추가 및 인증로직 도입
  src/main/java/com/brainpix/alarm/controller/AlarmController.java
Labels: ✨ feature, 📒 docs

#127 [DOCS] 메시지 관련 스웨거 명세 작성 및 인증로직 추가
  src/main/java/com/brainpix/message/controller/MessageController.java
Labels: ✨ feature, 📒 docs

#131 [REFACT] 댓글 관련 리팩토링 (#129)
  src/main/java/com/brainpix/post/controller/CommentController.java
  src/main/java/com/brainpix/post/service/CommentService.java
Labels: ♻️ refactoring

#139 [FIX] 머지 충돌 해결 (#138)
  src/main/java/com/brainpix/api/code/error/IdeaMarketErrorCode.java
  src/main/java/com/brainpix/api/code/error/RecruitmentErrorCode.java
  src/main/java/com/brainpix/post/service/CollaborationHubService.java
  src/main/java/com/brainpix/post/service/IdeaMarketService.java
Labels: 🔨 fix

#133 [REFACT] 요청 과제 및 협업 광장 모집신청 리팩토링
  src/main/java/com/brainpix/api/code/error/CollectionErrorCode.java
  src/main/java/com/brainpix/post/controller/CollaborationHubController.java
  src/main/java/com/brainpix/post/controller/RequestTaskCommandController.java
  src/main/java/com/brainpix/post/dto/ApplyCollaborationDto.java
  src/main/java/com/brainpix/post/dto/ApplyRequestTaskDto.java
  src/main/java/com/brainpix/post/service/CollaborationHubService.java
  src/main/java/com/brainpix/post/service/RequestTaskCommandService.java
Labels: ♻️ refactoring

#137 [FEAT] 마이페이지- 내가 작성한 게시물 관리 페이지 구현
  src/main/java/com/brainpix/joining/entity/purchasing/CollectionGathering.java
  src/main/java/com/brainpix/joining/entity/purchasing/IdeaMarketPurchasing.java
  src/main/java/com/brainpix/joining/entity/purchasing/Payment.java
  src/main/java/com/brainpix/joining/entity/purchasing/RequestTaskPurchasing.java
  src/main/java/com/brainpix/joining/repository/CollectionGatheringRepository.java
  src/main/java/com/brainpix/joining/repository/IdeaMarketPurchasingRepository.java
  src/main/java/com/brainpix/joining/repository/RequestTaskPurchasingRepository.java
  src/main/java/com/brainpix/post/controller/MyCollaborationController.java
  src/main/java/com/brainpix/post/controller/MyIdeaMarketController.java
  src/main/java/com/brainpix/post/controller/MyRequestTaskController.java
  src/main/java/com/brainpix/post/controller/SavedPostController.java
  src/main/java/com/brainpix/post/dto/PostCollaborationResponse.java
  src/main/java/com/brainpix/post/dto/PostIdeaMarketResponse.java
  src/main/java/com/brainpix/post/dto/PostRequestTaskResponse.java
  src/main/java/com/brainpix/post/dto/mypostdto/CollaborationApplicationStatusResponse.java
  src/main/java/com/brainpix/post/dto/mypostdto/CollaborationCurrentMemberResponse.java
  src/main/java/com/brainpix/post/dto/mypostdto/MyCollaborationHubDetailResponse.java
  src/main/java/com/brainpix/post/dto/mypostdto/MyIdeaMarketPostDetailResponse.java
  src/main/java/com/brainpix/post/dto/mypostdto/MyRequestTaskDetailResponse.java
  src/main/java/com/brainpix/post/dto/mypostdto/PurchaseInfoResponse.java
  src/main/java/com/brainpix/post/dto/mypostdto/RequestTaskApplicationStatusResponse.java
  src/main/java/com/brainpix/post/dto/mypostdto/RequestTaskCurrentMemberResponse.java
  src/main/java/com/brainpix/post/repository/CollaborationHubRepository.java
  src/main/java/com/brainpix/post/repository/RequestTaskRepository.java
  src/main/java/com/brainpix/post/service/SavedPostService.java
  src/main/java/com/brainpix/post/service/mypost/MyCollaborationHubService.java
  src/main/java/com/brainpix/post/service/mypost/MyIdeaMarketService.java
  src/main/java/com/brainpix/post/service/mypost/MyRequestTaskService.java
Labels: ✨ feature

#144 [FIX] 안쓰는 이미지 업로드 코드 주석처리했습니다.
  src/main/java/com/brainpix/profile/controller/ProfileController.java
  src/main/java/com/brainpix/profile/service/ProfileService.java
Labels: 🔨 fix

#150 [FIX] 게시글 조회 관련 스웨거 문제 수정 (#147)
  src/main/java/com/brainpix/post/controller/CollaborationHubController.java
  src/main/java/com/brainpix/post/controller/CommentController.java
  src/main/java/com/brainpix/post/controller/IdeaMarketController.java
  src/main/java/com/brainpix/post/controller/RequestTaskQueryController.java
  src/main/java/com/brainpix/post/dto/GetIdeaListDto.java
  src/main/java/com/brainpix/post/dto/GetPopularIdeaListDto.java
  src/main/java/com/brainpix/post/dto/GetPopularRequestTaskListDto.java
  src/main/java/com/brainpix/post/dto/GetRequestTaskListDto.java
Labels: 🐞 bug

#157 [FIX] 요청 과제, 협업 광장 신청 시 알람 발행 추가 (#150)
  src/main/java/com/brainpix/post/converter/GetCollaborationHubDetailDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetCollaborationHubListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetIdeaDetailDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetIdeaListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetPopularIdeaListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetPopularRequestTaskListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetRequestTaskDetailDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetRequestTaskListDtoConverter.java
  src/main/java/com/brainpix/post/service/CollaborationHubService.java
  src/main/java/com/brainpix/post/service/RequestTaskCommandService.java
Labels: 🔨 fix

#161 [FIX] 프로필 관련 API 들 스웨거 설정 + Dto 타입 수정
  src/main/java/com/brainpix/post/dto/MyDefaultPageIdeaListDto.java
  src/main/java/com/brainpix/profile/controller/MyPageController.java
  src/main/java/com/brainpix/profile/controller/ProfileController.java
  src/main/java/com/brainpix/profile/controller/PublicProfileController.java
  src/main/java/com/brainpix/profile/converter/MyProfileConverter.java
  src/main/java/com/brainpix/profile/converter/ProfileConverter.java
  src/main/java/com/brainpix/profile/converter/ProfilePostConverter.java
  src/main/java/com/brainpix/profile/dto/CompanyProfileResponseDto.java
  src/main/java/com/brainpix/profile/dto/IndividualProfileResponseDto.java
  src/main/java/com/brainpix/profile/dto/IndividualProfileUpdateDto.java
  src/main/java/com/brainpix/profile/dto/MyPageResponseDto.java
  src/main/java/com/brainpix/profile/dto/PublicProfileResponseDto.java
  src/main/java/com/brainpix/profile/service/MyPageService.java
Labels: 🔨 fix

#163 [FIX] 지원현황, 저장게시물 스웨거 설명 추가 , 응답값 ,타입 수정
  src/main/java/com/brainpix/joining/controller/SupportCollaborationController.java
  src/main/java/com/brainpix/joining/controller/SupportIdeaMarketController.java
  src/main/java/com/brainpix/joining/controller/SupportRequestTaskController.java
  src/main/java/com/brainpix/joining/converter/CollectionGatheringConverter.java
  src/main/java/com/brainpix/joining/converter/IdeaMarketPurchasingConverter.java
  src/main/java/com/brainpix/joining/converter/RequestTaskPurchasingConverter.java
  src/main/java/com/brainpix/joining/dto/AcceptedCollaborationDto.java
  src/main/java/com/brainpix/joining/dto/AcceptedRequestTaskPurchasingDto.java
  src/main/java/com/brainpix/joining/dto/IdeaMarketPurchaseDto.java
  src/main/java/com/brainpix/joining/dto/RejectedCollaborationDto.java
  src/main/java/com/brainpix/joining/dto/RejectedRequestTaskPurchasingDto.java
  src/main/java/com/brainpix/post/controller/MyCollaborationController.java
  src/main/java/com/brainpix/post/controller/MyIdeaMarketController.java
  src/main/java/com/brainpix/post/controller/MyRequestTaskController.java
  src/main/java/com/brainpix/post/dto/PostCollaborationResponse.java
  src/main/java/com/brainpix/post/dto/PostRequestTaskResponse.java
  src/main/java/com/brainpix/post/dto/mypostdto/MyCollaborationHubDetailResponse.java
  src/main/java/com/brainpix/post/dto/mypostdto/MyRequestTaskDetailResponse.java
Labels: 🔨 fix

#160 [REFACT] 포트폴리오 응답 타입 수정 및 리팩토링
  src/main/java/com/brainpix/profile/controller/PortfolioController.java
  src/main/java/com/brainpix/profile/dto/request/PortfolioRequest.java
  src/main/java/com/brainpix/profile/dto/request/SpecializationRequest.java
  src/main/java/com/brainpix/profile/dto/response/PortfolioDetailResponse.java
  src/main/java/com/brainpix/profile/dto/response/PortfolioResponse.java
  src/main/java/com/brainpix/profile/entity/Portfolio.java
  src/main/java/com/brainpix/profile/entity/Specialization.java
Labels: ♻️ refactoring

#165 [FIX] @Schema 추가
  src/main/java/com/brainpix/joining/controller/SupportCollaborationController.java
  src/main/java/com/brainpix/joining/dto/AcceptedCollaborationDto.java
  src/main/java/com/brainpix/joining/dto/AcceptedRequestTaskPurchasingDto.java
  src/main/java/com/brainpix/joining/dto/IdeaMarketPurchaseDto.java
  src/main/java/com/brainpix/joining/dto/RejectedCollaborationDto.java
  src/main/java/com/brainpix/joining/dto/RejectedRequestTaskPurchasingDto.java
  src/main/java/com/brainpix/joining/service/SupportCollaborationService.java
  src/main/java/com/brainpix/post/dto/PostCollaborationResponse.java
  src/main/java/com/brainpix/post/dto/PostRequestTaskResponse.java
  src/main/java/com/brainpix/post/dto/mypostdto/MyCollaborationHubDetailResponse.java
  src/main/java/com/brainpix/post/dto/mypostdto/MyRequestTaskDetailResponse.java
  src/main/java/com/brainpix/profile/dto/PublicProfileResponseDto.java
Labels: 🔨 fix

#167 [DOCS] 회원가입 API 스웨거 작성 (#166)
  src/main/java/com/brainpix/HealthHeckController.java
  src/main/java/com/brainpix/kafka/controller/KafkaProducerController.java
  src/main/java/com/brainpix/mail/controller/MailController.java
  src/main/java/com/brainpix/security/controller/SignUpController.java
Labels: 📒 docs

#169 [DOCS] 스웨거 가독성 증가 (#168)
  src/main/java/com/brainpix/alarm/controller/AlarmController.java
  src/main/java/com/brainpix/message/controller/MessageController.java
  src/main/java/com/brainpix/post/controller/CollaborationHubCommandController.java
  src/main/java/com/brainpix/post/controller/CollaborationHubQueryController.java
  src/main/java/com/brainpix/post/controller/IdeaMarketCommandController.java
  src/main/java/com/brainpix/post/controller/IdeaMarketQueryController.java
  src/main/java/com/brainpix/post/controller/RequestTaskCommandController.java
  src/main/java/com/brainpix/post/controller/RequestTaskQueryController.java
  src/main/java/com/brainpix/profile/controller/PortfolioController.java
Labels: 📒 docs

#155 [FEAT] 조회수 증가 로직 구현 (#152)
  src/main/java/com/brainpix/post/controller/CollaborationHubQueryController.java
  src/main/java/com/brainpix/post/dto/ApplyCollaborationDto.java
  src/main/java/com/brainpix/post/dto/ApplyRequestTaskDto.java
  src/main/java/com/brainpix/post/repository/PostRepository.java
  src/main/java/com/brainpix/post/service/CollaborationHubService.java
  src/main/java/com/brainpix/post/service/IdeaMarketService.java
  src/main/java/com/brainpix/post/service/RequestTaskQueryService.java
Labels: ✨ feature

#174 [BUG] 썸네일 npe 수정 (#173)
  src/main/java/com/brainpix/post/converter/GetIdeaDetailDtoConverter.java
Labels: 🐞 bug

#176 [BUG] @ElementCollection을 고려한 OutOfBound 해결 (#175)
  src/main/java/com/brainpix/post/converter/GetCollaborationHubDetailDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetCollaborationHubListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetIdeaDetailDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetIdeaListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetPopularIdeaListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetPopularRequestTaskListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetRequestTaskDetailDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetRequestTaskListDtoConverter.java
Labels: 🐞 bug

#177 [FEAT] 협업 광장 지원에 대해 수락,거절에 따른 알람 생성을 추가했습니다.
  src/main/java/com/brainpix/post/service/mypost/MyCollaborationHubService.java
Labels: ✨ feature

#179 [FIX] 상대방(개인/기업) 프로필 조회 ,수락/거절, 메시지 API를 위한 페이지에 정보 역할의 응답값 추가
  src/main/java/com/brainpix/joining/converter/CollectionGatheringConverter.java
  src/main/java/com/brainpix/joining/converter/IdeaMarketPurchasingConverter.java
  src/main/java/com/brainpix/joining/converter/RequestTaskPurchasingConverter.java
  src/main/java/com/brainpix/joining/dto/AcceptedCollaborationDto.java
  src/main/java/com/brainpix/joining/dto/AcceptedRequestTaskPurchasingDto.java
  src/main/java/com/brainpix/joining/dto/IdeaMarketPurchaseDto.java
  src/main/java/com/brainpix/joining/dto/RejectedCollaborationDto.java
  src/main/java/com/brainpix/joining/dto/RejectedRequestTaskPurchasingDto.java
  src/main/java/com/brainpix/joining/dto/TeamMemberInfoDto.java
  src/main/java/com/brainpix/post/dto/mypostdto/CollaborationApplicationStatusResponse.java
  src/main/java/com/brainpix/post/dto/mypostdto/CollaborationCurrentMemberResponse.java
  src/main/java/com/brainpix/post/dto/mypostdto/PurchaseInfoResponse.java
  src/main/java/com/brainpix/post/dto/mypostdto/RequestTaskApplicationStatusResponse.java
  src/main/java/com/brainpix/post/dto/mypostdto/RequestTaskCurrentMemberResponse.java
  src/main/java/com/brainpix/post/service/mypost/MyCollaborationHubService.java
  src/main/java/com/brainpix/post/service/mypost/MyIdeaMarketService.java
  src/main/java/com/brainpix/post/service/mypost/MyRequestTaskService.java
  src/main/java/com/brainpix/profile/converter/MyProfileConverter.java
  src/main/java/com/brainpix/profile/dto/CompanyProfileResponseDto.java
  src/main/java/com/brainpix/profile/dto/IndividualProfileResponseDto.java
Labels: 🔨 fix

#115 [FEAT] 카카오페이 결제 구현 (#71)
  src/main/java/com/brainpix/api/code/error/KakaoPayErrorCode.java
  src/main/java/com/brainpix/joining/entity/quantity/BaseQuantity.java
  src/main/java/com/brainpix/joining/repository/IdeaMarketPurchasingRepository.java
  src/main/java/com/brainpix/kakaopay/api_client/KakaoPayApiClient.java
  src/main/java/com/brainpix/kakaopay/controller/KakaoPayController.java
  src/main/java/com/brainpix/kakaopay/converter/KakaoPayApproveDtoConverter.java
  src/main/java/com/brainpix/kakaopay/converter/KakaoPayReadyDtoConverter.java
  src/main/java/com/brainpix/kakaopay/dto/KakaoPayApproveDto.java
  src/main/java/com/brainpix/kakaopay/dto/KakaoPayReadyDto.java
  src/main/java/com/brainpix/kakaopay/entity/KakaoPaymentData.java
  src/main/java/com/brainpix/kakaopay/repository/KakaoPaymentDataRepository.java
  src/main/java/com/brainpix/kakaopay/repository/NamedLockRepository.java
  src/main/java/com/brainpix/kakaopay/service/KakaoPayFacadeService.java
  src/main/java/com/brainpix/kakaopay/service/KakaoPayService.java
  src/main/resources/application-dev.yml
Labels: ✨ feature

#153 [FEAT] 아이디어 결제 페이지 구현 (#142)
  src/main/java/com/brainpix/post/controller/IdeaMarketQueryController.java
  src/main/java/com/brainpix/post/converter/GetIdeaPurchasePageDtoConverter.java
  src/main/java/com/brainpix/post/dto/GetIdeaPurchasePageDto.java
  src/main/java/com/brainpix/post/service/IdeaMarketService.java
Labels: ✨ feature

#184 [BUG] mongodb연동 설정 및 추가
  src/main/java/com/brainpix/BrainpixApplication.java
  src/main/java/com/brainpix/config/MongoConfig.java
  src/main/resources/application-dev.yml
Labels: 🐞 bug

#185 [FEAT] AWS S3 Presigned URL 생성 API 구현 (#99)
  build.gradle
  src/main/java/com/brainpix/config/S3Config.java
  src/main/java/com/brainpix/post/controller/FileUploadController.java
  src/main/java/com/brainpix/post/service/FileUploadService.java
  src/main/resources/application-dev.yml
Labels: ✨ feature

#186 [FEAT] 조회 시 내가 저장한 게시글인지, 내 게시글인지 확인하는 필드 추가 (#172)
  src/main/java/com/brainpix/post/controller/CollaborationHubQueryController.java
  src/main/java/com/brainpix/post/controller/CommentController.java
  src/main/java/com/brainpix/post/controller/IdeaMarketQueryController.java
  src/main/java/com/brainpix/post/controller/RequestTaskQueryController.java
  src/main/java/com/brainpix/post/converter/GetCollaborationHubDetailDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetCollaborationHubListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetCommentListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetIdeaDetailDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetIdeaListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetPopularIdeaListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetPopularRequestTaskListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetRequestTaskDetailDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetRequestTaskListDtoConverter.java
  src/main/java/com/brainpix/post/dto/GetCollaborationHubDetailDto.java
  src/main/java/com/brainpix/post/dto/GetCollaborationHubListDto.java
  src/main/java/com/brainpix/post/dto/GetCommentListDto.java
  src/main/java/com/brainpix/post/dto/GetIdeaDetailDto.java
  src/main/java/com/brainpix/post/dto/GetIdeaListDto.java
  src/main/java/com/brainpix/post/dto/GetPopularIdeaListDto.java
  src/main/java/com/brainpix/post/dto/GetPopularRequestTaskListDto.java
  src/main/java/com/brainpix/post/dto/GetRequestTaskDetailDto.java
  src/main/java/com/brainpix/post/dto/GetRequestTaskListDto.java
  src/main/java/com/brainpix/post/repository/CollaborationHubCustomRepository.java
  src/main/java/com/brainpix/post/repository/CollaborationHubCustomRepositoryImpl.java
  src/main/java/com/brainpix/post/repository/CommentRepository.java
  src/main/java/com/brainpix/post/repository/IdeaMarketCustomRepository.java
  src/main/java/com/brainpix/post/repository/IdeaMarketCustomRepositoryImpl.java
  src/main/java/com/brainpix/post/repository/RequestTaskCustomRepository.java
  src/main/java/com/brainpix/post/repository/RequestTaskCustomRepositoryImpl.java
  src/main/java/com/brainpix/post/repository/SavedPostRepository.java
  src/main/java/com/brainpix/post/service/CollaborationHubService.java
  src/main/java/com/brainpix/post/service/CommentService.java
  src/main/java/com/brainpix/post/service/IdeaMarketService.java
  src/main/java/com/brainpix/post/service/RequestTaskQueryService.java
Labels: ✨ feature

#189 [BUG]YearMonth 의 NotBlank를 NotNull로 수정했습니다.
  src/main/java/com/brainpix/profile/dto/request/PortfolioRequest.java
Labels: 🐞 bug

#191 [BUG] @RequestParam을 @UserId로 어노테이션 수정 (#190)
  src/main/java/com/brainpix/post/controller/CollaborationHubQueryController.java
Labels: 🐞 bug

#193 [BUG] 모집 id 추가 (#192)
  src/main/java/com/brainpix/post/converter/ApplyRequestTaskDtoConverter.java
Labels: 🐞 bug

#195 [FIX] 개인프로필-개별정보,기업프로필-기업정보 공개여부 상세 설정
  src/main/java/com/brainpix/profile/controller/ProfileController.java
  src/main/java/com/brainpix/profile/converter/MyProfileConverter.java
  src/main/java/com/brainpix/profile/converter/ProfileConverter.java
  src/main/java/com/brainpix/profile/dto/CompanyProfileResponseDto.java
  src/main/java/com/brainpix/profile/dto/CompanyProfileUpdateDto.java
  src/main/java/com/brainpix/profile/dto/IndividualProfileResponseDto.java
  src/main/java/com/brainpix/profile/dto/IndividualProfileUpdateDto.java
  src/main/java/com/brainpix/profile/entity/CompanyInformation.java
  src/main/java/com/brainpix/profile/entity/CompanyProfile.java
  src/main/java/com/brainpix/profile/entity/Contact.java
  src/main/java/com/brainpix/profile/entity/IndividualProfile.java
  src/main/java/com/brainpix/profile/service/ProfileService.java
  src/main/java/com/brainpix/profile/service/PublicProfileService.java
  src/main/java/com/brainpix/security/service/IndividualSignUpService.java
Labels: 🔨 fix

#199 [FIX] 구매 시 email 필드 추가 (#198)
  src/main/java/com/brainpix/api/code/error/IdeaMarketErrorCode.java
  src/main/java/com/brainpix/post/converter/GetIdeaPurchasePageDtoConverter.java
  src/main/java/com/brainpix/post/dto/GetIdeaPurchasePageDto.java
  src/main/java/com/brainpix/post/service/IdeaMarketService.java
Labels: 🔨 fix

#203 [FEAT] 메시지 전송 api 수정
  src/main/java/com/brainpix/message/converter/SendMessageConverter.java
  src/main/java/com/brainpix/message/dto/SendMessageDto.java
  src/main/java/com/brainpix/message/service/MessageService.java
Labels: ✨ feature

#209 [BUG] API 충돌 해결 및 정렬 기준 수정
  src/main/java/com/brainpix/profile/controller/PortfolioController.java
  src/main/java/com/brainpix/profile/controller/PublicProfileController.java
  src/main/java/com/brainpix/profile/service/PublicProfileService.java
Labels: 🐞 bug

#212 [FIX] 결제 시 리다이렉트 경로를 프론트 로컬 포트로 임시 변경 (#211)
  src/main/java/com/brainpix/kakaopay/api_client/KakaoPayApiClient.java
  src/main/java/com/brainpix/kakaopay/controller/KakaoPayController.java
Labels: 🔨 fix

#214 [BUG] gathering NPE방지를 위한 수정
  src/main/java/com/brainpix/profile/converter/ProfilePostConverter.java
Labels: 🐞 bug

#215 [FIX] 메시지 검색조건 변경 및 알림 응답값 변경
  src/main/java/com/brainpix/alarm/converter/GetAlarmConverter.java
  src/main/java/com/brainpix/alarm/dto/GetAlarmDto.java
  src/main/java/com/brainpix/message/controller/MessageController.java
  src/main/java/com/brainpix/message/converter/GetMessageListConverter.java
  src/main/java/com/brainpix/message/dto/GetMessageListDto.java
  src/main/java/com/brainpix/message/dto/MessageSearchType.java
  src/main/java/com/brainpix/message/repository/MessageRepository.java
  src/main/java/com/brainpix/message/service/MessageService.java
Labels: 🔨 fix

#219 [BUG] isRead 필드 추가하도록 변경
  src/main/java/com/brainpix/message/converter/SendMessageConverter.java
Labels: 🐞 bug

#221 [FIX] 메시지 조회 api 응답값 수정 (#220)
  src/main/java/com/brainpix/message/converter/GetMessageListConverter.java
  src/main/java/com/brainpix/message/dto/GetMessageListDto.java
  src/main/java/com/brainpix/message/dto/MessageType.java
  src/main/java/com/brainpix/message/service/MessageService.java
Labels: 🔨 fix

#224 [FIX] 조회 시 이름이 아닌 닉네임을 반환하도록 변경 (#223)
  src/main/java/com/brainpix/post/converter/GetCollaborationHubDetailDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetCollaborationHubListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetCommentListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetIdeaDetailDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetIdeaListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetIdeaPurchasePageDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetPopularIdeaListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetPopularRequestTaskListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetRequestTaskDetailDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetRequestTaskListDtoConverter.java
Labels: 🔨 fix

#225 [FIX] 마이페이지,프로필 조회시 이름 대신 닉네임으로변경
  src/main/java/com/brainpix/joining/converter/CollectionGatheringConverter.java
  src/main/java/com/brainpix/joining/converter/IdeaMarketPurchasingConverter.java
  src/main/java/com/brainpix/joining/converter/RequestTaskPurchasingConverter.java
  src/main/java/com/brainpix/joining/dto/AcceptedCollaborationDto.java
  src/main/java/com/brainpix/joining/dto/AcceptedRequestTaskPurchasingDto.java
  src/main/java/com/brainpix/joining/dto/IdeaMarketPurchaseDto.java
  src/main/java/com/brainpix/post/dto/PostCollaborationResponse.java
  src/main/java/com/brainpix/post/dto/PostIdeaMarketResponse.java
  src/main/java/com/brainpix/post/dto/PostRequestTaskResponse.java
  src/main/java/com/brainpix/profile/converter/MyProfileConverter.java
  src/main/java/com/brainpix/profile/converter/ProfilePostConverter.java
  src/main/java/com/brainpix/profile/dto/CompanyProfileResponseDto.java
  src/main/java/com/brainpix/profile/dto/IndividualProfileResponseDto.java
  src/main/java/com/brainpix/profile/dto/MyPageResponseDto.java
  src/main/java/com/brainpix/profile/service/MyPageService.java
  src/main/java/com/brainpix/profile/service/PublicProfileService.java
Labels: 🔨 fix

#227 [FIX] 협업 초기 인원을 2명 이상 등록하는 경우 오류 수정 (#226)
  src/main/java/com/brainpix/post/converter/GetCollaborationHubDetailDtoConverter.java
  src/main/java/com/brainpix/post/dto/GetCollaborationHubDetailDto.java
  src/main/java/com/brainpix/post/service/CollaborationHubInitialMemberService.java
Labels: 🐞 bug

#229 [FIX] ALL 타입 조회시 전송하거나 수신한 메시지 조회하도록 수정
  src/main/java/com/brainpix/message/repository/MessageRepository.java
  src/main/java/com/brainpix/message/service/MessageService.java
Labels: 🔨 fix

#232 [FIX] 결제 url 배포서버로 변경 및 IDEA_SOLUTION 수량 설정 (#230)
  src/main/java/com/brainpix/kakaopay/api_client/KakaoPayApiClient.java
  src/main/java/com/brainpix/post/converter/GetCollaborationHubDetailDtoConverter.java
  src/main/java/com/brainpix/post/dto/GetCollaborationHubDetailDto.java
  src/main/java/com/brainpix/post/service/IdeaMarketService.java
  src/main/resources/application-dev.yml
Labels: 🔨 fix

#234 [FEAT] 협업 광장 내 개최 인원 유저 고유 아이디 반환 API 구현 (#233)
  src/main/java/com/brainpix/post/controller/CollaborationHubCommandController.java
  src/main/java/com/brainpix/post/service/CollaborationHubInitialMemberService.java
Labels: ✨ feature

#236 [BUG] 아이디어 솔루션 등록 시 버그 수정 (#235)
  src/main/java/com/brainpix/joining/dto/IdeaMarketPriceDto.java
  src/main/java/com/brainpix/post/service/IdeaMarketService.java
Labels: 🐞 bug

#238 [REFACT] 상대방 게시글 조회 응답값(저장여부) 추가
  src/main/java/com/brainpix/post/dto/PostCollaborationResponse.java
  src/main/java/com/brainpix/post/dto/PostIdeaMarketResponse.java
  src/main/java/com/brainpix/post/dto/PostRequestTaskResponse.java
  src/main/java/com/brainpix/post/repository/SavedPostRepository.java
  src/main/java/com/brainpix/post/service/SavedPostService.java
  src/main/java/com/brainpix/post/service/mypost/MyCollaborationHubService.java
  src/main/java/com/brainpix/post/service/mypost/MyIdeaMarketService.java
  src/main/java/com/brainpix/post/service/mypost/MyRequestTaskService.java
  src/main/java/com/brainpix/profile/controller/PublicProfileController.java
  src/main/java/com/brainpix/profile/converter/ProfilePostConverter.java
  src/main/java/com/brainpix/profile/dto/PublicProfileResponseDto.java
  src/main/java/com/brainpix/profile/service/PublicProfileService.java
Labels: ♻️ refactoring

#242 [FIX] 결제 시, 실제 배포 서버로 리다이렉트 되도록 url 변경 (#241)
  src/main/resources/application-dev.yml
Labels: 🔨 fix

#205 [FEAT] 레디스 도입 및 조회/결제 동시성 처리 (#204)
  build.gradle
  src/main/java/com/brainpix/BrainpixApplication.java
  src/main/java/com/brainpix/api/code/error/KakaoPayErrorCode.java
  src/main/java/com/brainpix/config/RedisConfig.java
  src/main/java/com/brainpix/kakaopay/api_client/KakaoPayApiClient.java
  src/main/java/com/brainpix/kakaopay/controller/KakaoPayController.java
  src/main/java/com/brainpix/kakaopay/converter/KakaoPayApproveDtoConverter.java
  src/main/java/com/brainpix/kakaopay/converter/KakaoPayReadyDtoConverter.java
  src/main/java/com/brainpix/kakaopay/converter/KakaoPaymentDataDtoConverter.java
  src/main/java/com/brainpix/kakaopay/dto/KakaoPaymentDataDto.java
  src/main/java/com/brainpix/kakaopay/entity/KakaoPaymentData.java
  src/main/java/com/brainpix/kakaopay/repository/KakaoPaymentDataRepository.java
  src/main/java/com/brainpix/kakaopay/repository/NamedLockRepository.java
  src/main/java/com/brainpix/kakaopay/service/KakaoPayFacadeService.java
  src/main/java/com/brainpix/kakaopay/service/KakaoPayService.java
  src/main/java/com/brainpix/post/repository/PostRepository.java
  src/main/java/com/brainpix/post/service/CollaborationHubService.java
  src/main/java/com/brainpix/post/service/IdeaMarketService.java
  src/main/java/com/brainpix/post/service/RequestTaskQueryService.java
  src/main/java/com/brainpix/redis/service/RedisKakaoPayCacheService.java
  src/main/java/com/brainpix/redis/service/RedisViewCountService.java
Labels: ✨ feature, ♻️ refactoring
