Repository BrainPix/BrainPix-Back, pull requests merged in 2025-01, with the labels that each got.

#3 [FEAT] 프로젝트에 사용할 엔티티를 생성했습니다. (#2)
  build.gradle
  src/main/java/com/brainpix/joining/entity/purchasing/CollectionGathering.java
  src/main/java/com/brainpix/joining/entity/purchasing/IdeaMarketPurchasing.java
  src/main/java/com/brainpix/joining/entity/purchasing/RequestTaskPurchasing.java
  src/main/java/com/brainpix/joining/entity/quantity/BaseQuantity.java
  src/main/java/com/brainpix/joining/entity/quantity/Gathering.java
  src/main/java/com/brainpix/joining/entity/quantity/PaymentDuration.java
  src/main/java/com/brainpix/joining/entity/quantity/Price.java
  src/main/java/com/brainpix/jpa/BaseTimeEntity.java
  src/main/java/com/brainpix/jpa/JpaConfig.java
  src/main/java/com/brainpix/post/entity/BasePost.java
  src/main/java/com/brainpix/post/entity/collaboration_hub/CollaborationHub.java
  src/main/java/com/brainpix/post/entity/collaboration_hub/CollaborationRecruitment.java
  src/main/java/com/brainpix/post/entity/collaboration_hub/CollaborationType.java
  src/main/java/com/brainpix/post/entity/idea_market/IdeaMarket.java
  src/main/java/com/brainpix/post/entity/idea_market/IdeaMarketAuth.java
  src/main/java/com/brainpix/post/entity/idea_market/IdeaMarketType.java
  src/main/java/com/brainpix/post/entity/request_task/Comment.java
  src/main/java/com/brainpix/post/entity/request_task/RequestTask.java
  src/main/java/com/brainpix/post/entity/request_task/RequestTaskRecruitment.java
  src/main/java/com/brainpix/profile/entity/Career.java
  src/main/java/com/brainpix/profile/entity/CompanyProfile.java
  src/main/java/com/brainpix/profile/entity/Contact.java
  src/main/java/com/brainpix/profile/entity/ContactType.java
  src/main/java/com/brainpix/profile/entity/IndividualProfile.java
  src/main/java/com/brainpix/profile/entity/Portfolio.java
  src/main/java/com/brainpix/profile/entity/Profile.java
  src/main/java/com/brainpix/profile/entity/Specialization.java
  src/main/java/com/brainpix/profile/entity/Stack.java
  src/main/java/com/brainpix/profile/entity/StackProficiency.java
  src/main/java/com/brainpix/user/entity/Company.java
  src/main/java/com/brainpix/user/entity/Individual.java
  src/main/java/com/brainpix/user/entity/User.java
Labels: ✨ feature

#5 [FEAT] 공통 응답 및 에러처리를 구현하였습니다. (#1)
  src/main/java/com/brainpix/api/ApiResponse.java
  src/main/java/com/brainpix/api/code/error/CommonErrorCode.java
  src/main/java/com/brainpix/api/code/error/ErrorCode.java
  src/main/java/com/brainpix/api/code/success/CommonSuccessCode.java
  src/main/java/com/brainpix/api/code/success/SuccessCode.java
  src/main/java/com/brainpix/api/exception/BrainPixException.java
  src/main/java/com/brainpix/api/handler/ExceptionAdvice.java
Labels: ✨ feature

#12 [FIX] 협업 광장과 요청 과제의 컬럼을 변경합니다 (#11)
  src/main/java/com/brainpix/post/entity/BasePost.java
  src/main/java/com/brainpix/post/entity/IdeaMarketAuth.java
  src/main/java/com/brainpix/post/entity/collaboration_hub/CollaborationHub.java
  src/main/java/com/brainpix/post/entity/idea_market/IdeaMarket.java
  src/main/java/com/brainpix/post/entity/request_task/RequestTask.java
Labels: 🔨 fix

#8 [CI/CD] develop 브랜치로 merge 시, 도커 허브에 이미지를 푸시합니다. (#4)
  .github/workflows/develop_cd_workflow.yml
  Dockerfile
  build.gradle
  src/main/java/com/brainpix/jasypt/JasyptConfig.java
  src/main/resources/application-dev.yml
Labels: 🖧 cicd

#16 [CICD] 빌드된 jar파일 경로 설정 (#15)
  .github/workflows/develop_cd_workflow.yml
  build.gradle
Labels: 🖧 cicd

#13 [FEAT] 알림 관련 기능 프로토타입 구현 #7
  build.gradle
  src/main/java/com/brainpix/alarm/controller/AlarmController.java
  src/main/java/com/brainpix/alarm/converter/CreateAlarmConverter.java
  src/main/java/com/brainpix/alarm/converter/GetAlarmConverter.java
  src/main/java/com/brainpix/alarm/dto/CreateAlarmDto.java
  src/main/java/com/brainpix/alarm/dto/GetAlarmDto.java
  src/main/java/com/brainpix/alarm/dto/GetUnreadAlarmDto.java
  src/main/java/com/brainpix/alarm/model/Alarm.java
  src/main/java/com/brainpix/alarm/model/AlarmInfo.java
  src/main/java/com/brainpix/alarm/repository/AlarmRepository.java
  src/main/java/com/brainpix/alarm/service/AlarmService.java
  src/main/java/com/brainpix/alarm/template/AlarmTemplate.java
  src/main/java/com/brainpix/alarm/utils/AlarmInfoParser.java
  src/main/java/com/brainpix/api/code/error/AlarmErrorCode.java
  src/main/java/com/brainpix/config/MongoConfig.java
  src/main/java/com/brainpix/jpa/JpaConfig.java
Labels: ✨ feature

#19 [FEAT] 댓글 기능이 도든 글 유형에 적용되도록 변경 (#18)
  src/main/java/com/brainpix/post/entity/Comment.java
  src/main/java/com/brainpix/post/entity/Post.java
  src/main/java/com/brainpix/post/entity/collaboration_hub/CollaborationHub.java
  src/main/java/com/brainpix/post/entity/idea_market/IdeaMarket.java
  src/main/java/com/brainpix/post/entity/request_task/RequestTask.java
  src/main/java/com/brainpix/profile/entity/Profile.java
  src/main/java/com/brainpix/user/entity/User.java
Labels: ✨ feature

#22 [BUG] JpaConfig에 basePackages를 명시하여 리포지토리가 스캔되도록 합니다. (#21)
  src/main/java/com/brainpix/jpa/JpaConfig.java
Labels: 🐞 bug

#25 [REFACT] enum 클래스 이름, 패키지 경로 변경 (#24)
  src/main/java/com/brainpix/post/entity/Post.java
  src/main/java/com/brainpix/post/entity/PostAuth.java
  src/main/java/com/brainpix/post/entity/collaboration_hub/CollaborationHub.java
  src/main/java/com/brainpix/post/entity/collaboration_hub/CollaborationType.java
  src/main/java/com/brainpix/post/entity/idea_market/IdeaMarket.java
  src/main/java/com/brainpix/post/entity/request_task/RequestTask.java
  src/main/java/com/brainpix/post/entity/request_task/RequestTaskType.java
Labels: ♻️ refactoring

#37 [FIX] Post 카테고리와 관련된 부분을 수정합니다 (#36)
  src/main/java/com/brainpix/post/entity/Post.java
  src/main/java/com/brainpix/post/entity/collaboration_hub/CollaborationHub.java
  src/main/java/com/brainpix/post/entity/idea_market/IdeaMarket.java
  src/main/java/com/brainpix/post/entity/request_task/RequestTask.java
Labels: 🔨 fix

#38 [FEAT] 카프카 연동 및 테스트용 코드 작성 (#23)
  build.gradle
  docker-compose-kafaka.yml
  src/main/java/com/brainpix/config/KafkaConsumerConfig.java
  src/main/java/com/brainpix/config/KafkaProducerConfig.java
  src/main/java/com/brainpix/kafka/controller/KafkaProducerController.java
  src/main/java/com/brainpix/kafka/service/KafkaListenerService.java
  src/main/java/com/brainpix/kafka/service/KafkaProducerService.java
Labels: ✨ feature

#31 [FEAT] 요청 과제 등록, 수정, 삭제 API 구현 (#10)
  build.gradle
  src/main/java/com/brainpix/api/code/error/PostErrorCode.java
  src/main/java/com/brainpix/api/code/error/PriceErrorCode.java
  src/main/java/com/brainpix/api/code/error/RequestTaskErrorCode.java
  src/main/java/com/brainpix/joining/converter/CreatePriceConverter.java
  src/main/java/com/brainpix/joining/dto/PriceDto.java
  src/main/java/com/brainpix/joining/entity/quantity/BaseQuantity.java
  src/main/java/com/brainpix/joining/entity/quantity/Price.java
  src/main/java/com/brainpix/joining/repository/PriceRepository.java
  src/main/java/com/brainpix/joining/service/PriceService.java
  src/main/java/com/brainpix/post/controller/RequestTaskController.java
  src/main/java/com/brainpix/post/controller/RequestTaskRecruitmentController.java
  src/main/java/com/brainpix/post/converter/CreateRequestTaskConverter.java
  src/main/java/com/brainpix/post/converter/CreateRequestTaskRecruitmentConverter.java
  src/main/java/com/brainpix/post/dto/PostDto.java
  src/main/java/com/brainpix/post/dto/RequestTaskApiResponseDto.java
  src/main/java/com/brainpix/post/dto/RequestTaskCreateDto.java
  src/main/java/com/brainpix/post/dto/RequestTaskRecruitmentDto.java
  src/main/java/com/brainpix/post/dto/RequestTaskUpdateDto.java
  src/main/java/com/brainpix/post/dto/RequestTaskWithRecruitmentsDto.java
  src/main/java/com/brainpix/post/entity/Post.java
  src/main/java/com/brainpix/post/entity/request_task/RequestTask.java
  src/main/java/com/brainpix/post/entity/request_task/RequestTaskRecruitment.java
  src/main/java/com/brainpix/post/repository/RequestTaskRecruitmentRepository.java
  src/main/java/com/brainpix/post/repository/RequestTaskRepository.java
  src/main/java/com/brainpix/post/service/RequestTaskRecruitmentService.java
  src/main/java/com/brainpix/post/service/RequestTaskService.java
  src/main/java/com/brainpix/user/entity/Individual.java
  src/main/java/com/brainpix/user/entity/User.java
  src/main/java/com/brainpix/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: ✨ feature

#28 [FEAT] 아이디어 메인 페이지 전체 조회/상세 조회, POST 댓글 조회, QueryDSL 설정 (#14)
  build.gradle
  src/main/java/com/brainpix/config/QueryDSLConfig.java
  src/main/java/com/brainpix/joining/repository/CollectionGatheringRepository.java
  src/main/java/com/brainpix/post/controller/IdeaMarketController.java
  src/main/java/com/brainpix/post/converter/GetIdeaCommentListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetIdeaDetailDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetIdeaListDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetPopularIdeaListDtoConverter.java
  src/main/java/com/brainpix/post/dto/GetIdeaCommentListDto.java
  src/main/java/com/brainpix/post/dto/GetIdeaDetailDto.java
  src/main/java/com/brainpix/post/dto/GetIdeaListDto.java
  src/main/java/com/brainpix/post/dto/GetPopularIdeaListDto.java
  src/main/java/com/brainpix/post/entity/SavedPost.java
  src/main/java/com/brainpix/post/enums/PostBooleanExpression.java
  src/main/java/com/brainpix/post/enums/SortType.java
  src/main/java/com/brainpix/post/repository/CommentCustomRepository.java
  src/main/java/com/brainpix/post/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/brainpix/post/repository/CommentRepository.java
  src/main/java/com/brainpix/post/repository/IdeaMarketCustomRepository.java
  src/main/java/com/brainpix/post/repository/IdeaMarketCustomRepositoryImpl.java
  src/main/java/com/brainpix/post/repository/IdeaMarketRepository.java
  src/main/java/com/brainpix/post/repository/SavedPostRepository.java
  src/main/java/com/brainpix/post/service/IdeaMarketService.java
Labels: ✨ feature

#41 [FEAT]: 저장 게시판 관리 페이지 구현(#32)
  build.gradle
  src/main/java/com/brainpix/api/code/error/SavedPostErrorCode.java
  src/main/java/com/brainpix/post/controller/SavedPostController.java
  src/main/java/com/brainpix/post/dto/SavedPostCollaborationResponse.java
  src/main/java/com/brainpix/post/dto/SavedPostIdeaMarketResponse.java
  src/main/java/com/brainpix/post/dto/SavedPostRequestTaskResponse.java
  src/main/java/com/brainpix/post/entity/Post.java
  src/main/java/com/brainpix/post/entity/SavedPost.java
  src/main/java/com/brainpix/post/entity/collaboration_hub/CollaborationHub.java
  src/main/java/com/brainpix/post/entity/request_task/RequestTask.java
  src/main/java/com/brainpix/post/repository/PostRepository.java
  src/main/java/com/brainpix/post/repository/SavedPostRepository.java
  src/main/java/com/brainpix/post/repository/SavedPostRepositoryCustom.java
  src/main/java/com/brainpix/post/repository/SavedPostRepositoryImpl.java
  src/main/java/com/brainpix/post/service/SavedPostService.java
  src/main/java/com/brainpix/profile/repository/UserRepository.java
  src/main/java/com/brainpix/profile/service/PortfolioService.java
  src/test/java/com/brainpix/profile/PortfolioServiceTest.java
Labels: ✨ feature

#46 [FEAT] 알림 생성 로직 메시지큐 연동 (#45)
  src/main/java/com/brainpix/alarm/controller/AlarmController.java
  src/main/java/com/brainpix/alarm/converter/CreateAlarmConverter.java
  src/main/java/com/brainpix/alarm/dto/AlarmEventDto.java
  src/main/java/com/brainpix/alarm/service/AlarmService.java
  src/main/java/com/brainpix/alarm/template/AlarmType.java
  src/main/java/com/brainpix/kafka/service/AlarmEventListener.java
  src/main/java/com/brainpix/kafka/service/AlarmEventService.java
Labels: ✨ feature

#47 [FEAT] 회원가입 로직 작성 (#20)
  build.gradle
  src/main/java/com/brainpix/api/code/error/SecurityErrorCode.java
  src/main/java/com/brainpix/profile/entity/CompanyProfile.java
  src/main/java/com/brainpix/profile/entity/IndividualProfile.java
  src/main/java/com/brainpix/profile/entity/Profile.java
  src/main/java/com/brainpix/security/HashEncoderConfig.java
  src/main/java/com/brainpix/security/SecurityConfig.java
  src/main/java/com/brainpix/security/controller/SignUpController.java
  src/main/java/com/brainpix/security/dto/request/SignUpRequest.java
  src/main/java/com/brainpix/security/service/CompanySignUpService.java
  src/main/java/com/brainpix/security/service/IndividualSignUpService.java
  src/main/java/com/brainpix/security/service/SignUpService.java
  src/main/java/com/brainpix/user/entity/User.java
  src/main/java/com/brainpix/user/repository/UserRepository.java
Labels: ✨ feature

#55 [FEAT] 초기 인원인지 확인하는 필드 추가 (#54)
  src/main/java/com/brainpix/joining/entity/purchasing/CollectionGathering.java
Labels: ✨ feature

#56 [FEAT] 아이디어 마켓 등록, 수정, 삭제 API 구현 (#33)
  src/main/java/com/brainpix/api/code/error/IdeaMarketErrorCode.java
  src/main/java/com/brainpix/joining/converter/CreateIdeaMarketPriceConverter.java
  src/main/java/com/brainpix/joining/dto/IdeaMarketPriceDto.java
  src/main/java/com/brainpix/joining/service/PriceService.java
  src/main/java/com/brainpix/post/controller/IdeaMarketController.java
  src/main/java/com/brainpix/post/converter/CreateIdeaMarketConverter.java
  src/main/java/com/brainpix/post/dto/IdeaMarketApiResponseDto.java
  src/main/java/com/brainpix/post/dto/IdeaMarketCreateDto.java
  src/main/java/com/brainpix/post/dto/IdeaMarketUpdateDto.java
  src/main/java/com/brainpix/post/entity/Post.java
  src/main/java/com/brainpix/post/entity/idea_market/IdeaMarket.java
  src/main/java/com/brainpix/post/repository/IdeaMarketRepository.java
  src/main/java/com/brainpix/post/service/IdeaMarketService.java
  src/main/java/com/brainpix/user/repository/UserRepository.java
Labels: ✨ feature

#69 [FEAT] 스웨거 설정 (#68)
  build.gradle
  src/main/java/com/brainpix/config/SwaggerConfig.java
Labels: ✨ feature

#73 [BUG] 깃 충돌로 주석 처리된 코드 복구 (#72)
  src/main/java/com/brainpix/joining/service/PriceService.java
Labels: 🐞 bug

#75 [FIX] Career 엔티티 수정
  src/main/java/com/brainpix/profile/entity/Contact.java
Labels: 🔨 fix

#58 [FEAT] 협업 광장 전체 조회 및 상세 조회 구현 (#35)
  src/main/java/com/brainpix/joining/repository/CollectionGatheringRepository.java
  src/main/java/com/brainpix/post/controller/CollaborationHubController.java
  src/main/java/com/brainpix/post/converter/GetCollaborationHubDetailDtoConverter.java
  src/main/java/com/brainpix/post/converter/GetCollaborationHubListDtoConverter.java
  src/main/java/com/brainpix/post/dto/GetCollaborationHubDetailDto.java
  src/main/java/com/brainpix/post/dto/GetCollaborationHubListDto.java
  src/main/java/com/brainpix/post/enums/PostBooleanExpression.java
  src/main/java/com/brainpix/post/enums/SortType.java
  src/main/java/com/brainpix/post/repository/CollaborationHubCustomRepository.java
  src/main/java/com/brainpix/post/repository/CollaborationHubCustomRepositoryImpl.java
  src/main/java/com/brainpix/post/repository/CollaborationHubRepository.java
  src/main/java/com/brainpix/post/repository/IdeaMarketCustomRepositoryImpl.java
  src/main/java/com/brainpix/post/service/CollaborationHubService.java
Labels: ✨ feature

#80 [FIX] 포트폴리오 엔티티 대표사진 필드 추가 (+ 엔티티 수정에 따른 포폴관련 코드 수정)
  src/main/java/com/brainpix/profile/dto/request/PortfolioRequest.java
  src/main/java/com/brainpix/profile/dto/response/PortfolioDetailResponse.java
  src/main/java/com/brainpix/profile/dto/response/PortfolioResponse.java
  src/main/java/com/brainpix/profile/entity/Portfolio.java
  src/main/java/com/brainpix/profile/service/PortfolioService.java
Labels: 🔨 fix
